version: '2.1'
services:
    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    staging:
        image: postgres:9.6
        restart: always
        ports:
            - "5432:5432"
        environment: 
            - POSTGRES_USER=staging
            - POSTGRES_PASSWORD=staging
            - POSTGRES_DB=staging
    webserver:
        image: devtechieinteractive/apache-airflow:1.10.1
        restart: always
        depends_on:
            - postgres
            - staging
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - /Users/rohithreddykota/Personal/Projects/airflow/covid19/dags:/usr/local/airflow/dags
        ports:
            - "8088:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 60s
            timeout: 90s
            retries: 3
